In [1]:
import numpy as np

In [3]:
k=np.array([1,2,3,4,5])
k

array([1, 2, 3, 4, 5])

In [6]:
k1=np.array([1,2,3],[6,4,5],[20,78,4])
k1

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [7]:
k.size

5

In [8]:
k.shape

(5,)

In [10]:
k.dtype

dtype('int32')

In [18]:
p=np.ones(2,dtype=int)
p

array([1, 1])

In [22]:
l=np.ones(9,dtype=int).reshape(3,3)
l

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [24]:
j=np.zeros(12,dtype=bool).reshape(3,4)
j

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [27]:
d=np.empty(3)
d

array([8.56235455e-312, 0.00000000e+000, 1.87138809e-310])

In [28]:
w=np.arange(10,78)
w

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77])

In [30]:
w=np.arange(10,78,2)
w

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76])

In [32]:
w=np.linspace(10,78,16)
w

array([10.        , 14.53333333, 19.06666667, 23.6       , 28.13333333,
       32.66666667, 37.2       , 41.73333333, 46.26666667, 50.8       ,
       55.33333333, 59.86666667, 64.4       , 68.93333333, 73.46666667,
       78.        ])

In [33]:
w=np.linspace(100,500,250)
w

array([100.        , 101.6064257 , 103.21285141, 104.81927711,
       106.42570281, 108.03212851, 109.63855422, 111.24497992,
       112.85140562, 114.45783133, 116.06425703, 117.67068273,
       119.27710843, 120.88353414, 122.48995984, 124.09638554,
       125.70281124, 127.30923695, 128.91566265, 130.52208835,
       132.12851406, 133.73493976, 135.34136546, 136.94779116,
       138.55421687, 140.16064257, 141.76706827, 143.37349398,
       144.97991968, 146.58634538, 148.19277108, 149.79919679,
       151.40562249, 153.01204819, 154.6184739 , 156.2248996 ,
       157.8313253 , 159.437751  , 161.04417671, 162.65060241,
       164.25702811, 165.86345382, 167.46987952, 169.07630522,
       170.68273092, 172.28915663, 173.89558233, 175.50200803,
       177.10843373, 178.71485944, 180.32128514, 181.92771084,
       183.53413655, 185.14056225, 186.74698795, 188.35341365,
       189.95983936, 191.56626506, 193.17269076, 194.77911647,
       196.38554217, 197.99196787, 199.59839357, 201.20

In [34]:
a=np.linspace(10,30,9).reshape(3,3)
a

array([[10. , 12.5, 15. ],
       [17.5, 20. , 22.5],
       [25. , 27.5, 30. ]])

In [35]:
a.transpose()

array([[10. , 17.5, 25. ],
       [12.5, 20. , 27.5],
       [15. , 22.5, 30. ]])

In [36]:
b=np.linspace(8,67,9).reshape(3,3)
b

array([[ 8.   , 15.375, 22.75 ],
       [30.125, 37.5  , 44.875],
       [52.25 , 59.625, 67.   ]])

In [37]:
a+d

array([[10. , 12.5, 15. ],
       [17.5, 20. , 22.5],
       [25. , 27.5, 30. ]])

In [38]:
a.add(b)

AttributeError: 'numpy.ndarray' object has no attribute 'add'

In [39]:
np.add(a,b)

array([[18.   , 27.875, 37.75 ],
       [47.625, 57.5  , 67.375],
       [77.25 , 87.125, 97.   ]])

In [40]:
a-b

array([[  2.   ,  -2.875,  -7.75 ],
       [-12.625, -17.5  , -22.375],
       [-27.25 , -32.125, -37.   ]])

In [41]:
np.subtract(a,b)

array([[  2.   ,  -2.875,  -7.75 ],
       [-12.625, -17.5  , -22.375],
       [-27.25 , -32.125, -37.   ]])

In [42]:
a/b

array([[1.25      , 0.81300813, 0.65934066],
       [0.58091286, 0.53333333, 0.50139276],
       [0.4784689 , 0.46121593, 0.44776119]])

In [43]:
np.divide(a,b)

array([[1.25      , 0.81300813, 0.65934066],
       [0.58091286, 0.53333333, 0.50139276],
       [0.4784689 , 0.46121593, 0.44776119]])

In [44]:
a*b

array([[  80.    ,  192.1875,  341.25  ],
       [ 527.1875,  750.    , 1009.6875],
       [1306.25  , 1639.6875, 2010.    ]])

In [45]:
np.multiply(a,b)

array([[  80.    ,  192.1875,  341.25  ],
       [ 527.1875,  750.    , 1009.6875],
       [1306.25  , 1639.6875, 2010.    ]])

In [46]:
a@b

array([[1240.3125, 1516.875 , 1793.4375],
       [1918.125 , 2360.625 , 2803.125 ],
       [2595.9375, 3204.375 , 3812.8125]])

In [47]:
a.dot(b)

array([[1240.3125, 1516.875 , 1793.4375],
       [1918.125 , 2360.625 , 2803.125 ],
       [2595.9375, 3204.375 , 3812.8125]])

In [48]:
a.max()

30.0

In [49]:
a.argmax()

8

In [50]:
a.max(axis=0)

array([25. , 27.5, 30. ])

In [51]:
a.max(axis=1)

array([15. , 22.5, 30. ])

In [52]:
a

array([[10. , 12.5, 15. ],
       [17.5, 20. , 22.5],
       [25. , 27.5, 30. ]])

In [53]:
a.min()

10.0

In [54]:
a.argmin()

0

In [ ]:
a.min(axis=0)