In [1]:
import numpy as np

In [3]:
a=np.linspace(10,200,9).reshape(3,3)
a

array([[ 10.  ,  33.75,  57.5 ],
       [ 81.25, 105.  , 128.75],
       [152.5 , 176.25, 200.  ]])

In [4]:
np.mean(a)

105.0

In [5]:
np.sqrt(a)

array([[ 3.16227766,  5.80947502,  7.58287544],
       [ 9.01387819, 10.24695077, 11.34680572],
       [12.34908904, 13.27591805, 14.14213562]])

In [6]:
np.std(a)

61.322236314950764

In [7]:
np.exp(a)

array([[2.20264658e+04, 4.54400462e+14, 9.37416750e+24],
       [1.93386723e+35, 3.98951957e+45, 8.23027876e+55],
       [1.69788585e+66, 3.50269591e+76, 7.22597377e+86]])

In [8]:
np.log(a)

array([[2.30258509, 3.51898042, 4.05178495],
       [4.39753082, 4.65396035, 4.85787254],
       [5.0271646 , 5.17190344, 5.29831737]])

In [9]:
np.log10(a)

array([[1.        , 1.52827378, 1.75966784],
       [1.90982337, 2.0211893 , 2.10974724],
       [2.18326984, 2.24612913, 2.30103   ]])

In [10]:
c=np.arange(1,101).reshape(10,10)
c

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [12]:
c[0,1]

2

In [13]:
c[:,0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [15]:
c[:,0].reshape(2,5)

array([[ 1, 11, 21, 31, 41],
       [51, 61, 71, 81, 91]])

In [16]:
c[:,0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [17]:
c[1:5,2:5]

array([[13, 14, 15],
       [23, 24, 25],
       [33, 34, 35],
       [43, 44, 45]])

In [18]:
c[:,1:4]

array([[ 2,  3,  4],
       [12, 13, 14],
       [22, 23, 24],
       [32, 33, 34],
       [42, 43, 44],
       [52, 53, 54],
       [62, 63, 64],
       [72, 73, 74],
       [82, 83, 84],
       [92, 93, 94]])

In [19]:
c[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [20]:
c.itemsize

4

In [21]:
c.dtype

dtype('int32')

In [22]:
x=np.arange(1,17).reshape(4,4)
y=np.arange(17,33).reshape(4,4)
x
y

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [23]:
y

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [24]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
np.concatenate((x,y))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [27]:
np.concatenate((x,y),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [28]:
np.vstack((x,y))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [29]:
np.hstack((x,y))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])